# Generated by Django 3.2.23 on 2024-01-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='department',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='university',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
