# Generated by Django 3.2.23 on 2024-01-02 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_professor_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='professor',
            unique_together={('name', 'title', 'research_areas', 'university', 'department')},
        ),
    ]
