# Generated by Django 3.2.23 on 2024-01-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_collegel_professor_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
