# Generated by Django 3.2.23 on 2024-01-08 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_professor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='college',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='school',
        ),
    ]
