# Generated by Django 3.2.23 on 2024-01-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20240108_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
