# Generated by Django 3.2.23 on 2024-01-24 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_professor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='university_world_ranking',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
