# Generated by Django 3.2.23 on 2024-01-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20240124_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='rating',
        ),
    ]
