# Generated by Django 3.2.23 on 2024-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_professor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
