# Generated by Django 3.2.23 on 2024-01-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_professor_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='rating',
        ),
    ]
