# Generated by Django 3.2.23 on 2024-02-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
