# Generated by Django 3.2.23 on 2024-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_professor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
