# Generated by Django 3.2.23 on 2024-02-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_professor_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='draft',
        ),
    ]
