# Generated by Django 3.2.23 on 2024-01-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
